apiVersion: v1
kind: Service
metadata:
    name: "gcp-firestore-emulator"
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    app: gcp-firestore-emulator
  type: LoadBalancer
status:
  loadBalancer: {}
